/*
 * Created on 4 Jul 2016 ( Time 10:15:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.web.listitem;

import com.kumasi.techjournal.domain.Application;
import com.kumasi.techjournal.web.common.ListItem;

public class ApplicationListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ApplicationListItem(Application application) {
		super();

		this.value = ""
			 + application.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = application.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
