/*
 * Created on 2 Jul 2016 ( Time 10:09:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.techjournal.domain.Application;
import com.kumasi.techjournal.domain.jpa.ApplicationEntity;
import com.kumasi.techjournal.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ApplicationServiceMapperTest {

	private ApplicationServiceMapper applicationServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		applicationServiceMapper = new ApplicationServiceMapper();
		applicationServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ApplicationEntity' to 'Application'
	 * @param applicationEntity
	 */
	@Test
	public void testMapApplicationEntityToApplication() {
		// Given
		ApplicationEntity applicationEntity = new ApplicationEntity();
		applicationEntity.setName(mockValues.nextString(45));
		
		// When
		Application application = applicationServiceMapper.mapApplicationEntityToApplication(applicationEntity);
		
		// Then
		assertEquals(applicationEntity.getName(), application.getName());
	}
	
	/**
	 * Test : Mapping from 'Application' to 'ApplicationEntity'
	 */
	@Test
	public void testMapApplicationToApplicationEntity() {
		// Given
		Application application = new Application();
		application.setName(mockValues.nextString(45));

		ApplicationEntity applicationEntity = new ApplicationEntity();
		
		// When
		applicationServiceMapper.mapApplicationToApplicationEntity(application, applicationEntity);
		
		// Then
		assertEquals(application.getName(), applicationEntity.getName());
	}

}