/*
 * Created on 2 Jul 2016 ( Time 10:09:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.techjournal.domain.SourceType;
import com.kumasi.techjournal.domain.jpa.SourceTypeEntity;
import com.kumasi.techjournal.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class SourceTypeServiceMapperTest {

	private SourceTypeServiceMapper sourceTypeServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		sourceTypeServiceMapper = new SourceTypeServiceMapper();
		sourceTypeServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'SourceTypeEntity' to 'SourceType'
	 * @param sourceTypeEntity
	 */
	@Test
	public void testMapSourceTypeEntityToSourceType() {
		// Given
		SourceTypeEntity sourceTypeEntity = new SourceTypeEntity();
		sourceTypeEntity.setCodeName(mockValues.nextString(45));
		
		// When
		SourceType sourceType = sourceTypeServiceMapper.mapSourceTypeEntityToSourceType(sourceTypeEntity);
		
		// Then
		assertEquals(sourceTypeEntity.getCodeName(), sourceType.getCodeName());
	}
	
	/**
	 * Test : Mapping from 'SourceType' to 'SourceTypeEntity'
	 */
	@Test
	public void testMapSourceTypeToSourceTypeEntity() {
		// Given
		SourceType sourceType = new SourceType();
		sourceType.setCodeName(mockValues.nextString(45));

		SourceTypeEntity sourceTypeEntity = new SourceTypeEntity();
		
		// When
		sourceTypeServiceMapper.mapSourceTypeToSourceTypeEntity(sourceType, sourceTypeEntity);
		
		// Then
		assertEquals(sourceType.getCodeName(), sourceTypeEntity.getCodeName());
	}

}