/*
 * Created on 1 Jul 2016 ( Time 19:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.kumasi.techjournal.web.common.AbstractController;
import com.kumasi.techjournal.web.common.FormMode;
import com.kumasi.techjournal.web.common.Message;
import com.kumasi.techjournal.web.common.MessageType;

//--- Entities
import com.kumasi.techjournal.domain.BatchJob;
import com.kumasi.techjournal.domain.ReleaseNote;

//--- Services 
import com.kumasi.techjournal.business.service.BatchJobService;
import com.kumasi.techjournal.business.service.ReleaseNoteService;

//--- List Items 
import com.kumasi.techjournal.web.listitem.ReleaseNoteListItem;

/**
 * Spring MVC controller for 'BatchJob' management.
 */
@Controller
@RequestMapping("/batchJob")
public class BatchJobController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "batchJob";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "batchJob/form";
	private static final String JSP_LIST   = "batchJob/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/batchJob/create";
	private static final String SAVE_ACTION_UPDATE   = "/batchJob/update";

	//--- Main entity service
	@Resource
    private BatchJobService batchJobService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private ReleaseNoteService releaseNoteService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public BatchJobController() {
		super(BatchJobController.class, MAIN_ENTITY_NAME );
		log("BatchJobController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "ReleaseNote"
	 * @param model
	 */
	private void populateListOfReleaseNoteItems(Model model) {
		List<ReleaseNote> list = releaseNoteService.findAll();
		List<ReleaseNoteListItem> items = new LinkedList<ReleaseNoteListItem>();
		for ( ReleaseNote releaseNote : list ) {
			items.add(new ReleaseNoteListItem( releaseNote ) );
		}
		model.addAttribute("listOfReleaseNoteItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param batchJob
	 */
	private void populateModel(Model model, BatchJob batchJob, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, batchJob);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfReleaseNoteItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfReleaseNoteItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of BatchJob found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<BatchJob> list = batchJobService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new BatchJob
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		BatchJob batchJob = new BatchJob();	
		populateModel( model, batchJob, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing BatchJob
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		BatchJob batchJob = batchJobService.findById(id);
		populateModel( model, batchJob, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param batchJob  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid BatchJob batchJob, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				BatchJob batchJobCreated = batchJobService.create(batchJob); 
				model.addAttribute(MAIN_ENTITY_NAME, batchJobCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, batchJob.getId() );
			} else {
				populateModel( model, batchJob, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "batchJob.error.create", e);
			populateModel( model, batchJob, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param batchJob  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid BatchJob batchJob, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				BatchJob batchJobSaved = batchJobService.update(batchJob);
				model.addAttribute(MAIN_ENTITY_NAME, batchJobSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, batchJob.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, batchJob, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "batchJob.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, batchJob, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			batchJobService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "batchJob.error.delete", e);
		}
		return redirectToList();
	}

}
