/*
 * Created on 1 Jul 2016 ( Time 19:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.kumasi.techjournal.web.common.AbstractController;
import com.kumasi.techjournal.web.common.FormMode;
import com.kumasi.techjournal.web.common.Message;
import com.kumasi.techjournal.web.common.MessageType;

//--- Entities
import com.kumasi.techjournal.domain.ReleaseNote;
import com.kumasi.techjournal.domain.TechNote;

//--- Services 
import com.kumasi.techjournal.business.service.ReleaseNoteService;
import com.kumasi.techjournal.business.service.TechNoteService;

//--- List Items 
import com.kumasi.techjournal.web.listitem.TechNoteListItem;

/**
 * Spring MVC controller for 'ReleaseNote' management.
 */
@Controller
@RequestMapping("/releaseNote")
public class ReleaseNoteController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "releaseNote";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "releaseNote/form";
	private static final String JSP_LIST   = "releaseNote/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/releaseNote/create";
	private static final String SAVE_ACTION_UPDATE   = "/releaseNote/update";

	//--- Main entity service
	@Resource
    private ReleaseNoteService releaseNoteService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private TechNoteService techNoteService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public ReleaseNoteController() {
		super(ReleaseNoteController.class, MAIN_ENTITY_NAME );
		log("ReleaseNoteController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "TechNote"
	 * @param model
	 */
	private void populateListOfTechNoteItems(Model model) {
		List<TechNote> list = techNoteService.findAll();
		List<TechNoteListItem> items = new LinkedList<TechNoteListItem>();
		for ( TechNote techNote : list ) {
			items.add(new TechNoteListItem( techNote ) );
		}
		model.addAttribute("listOfTechNoteItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param releaseNote
	 */
	private void populateModel(Model model, ReleaseNote releaseNote, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, releaseNote);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfTechNoteItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfTechNoteItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of ReleaseNote found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<ReleaseNote> list = releaseNoteService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new ReleaseNote
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		ReleaseNote releaseNote = new ReleaseNote();	
		populateModel( model, releaseNote, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing ReleaseNote
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		ReleaseNote releaseNote = releaseNoteService.findById(id);
		populateModel( model, releaseNote, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param releaseNote  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid ReleaseNote releaseNote, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				ReleaseNote releaseNoteCreated = releaseNoteService.create(releaseNote); 
				model.addAttribute(MAIN_ENTITY_NAME, releaseNoteCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, releaseNote.getId() );
			} else {
				populateModel( model, releaseNote, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "releaseNote.error.create", e);
			populateModel( model, releaseNote, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param releaseNote  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid ReleaseNote releaseNote, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				ReleaseNote releaseNoteSaved = releaseNoteService.update(releaseNote);
				model.addAttribute(MAIN_ENTITY_NAME, releaseNoteSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, releaseNote.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, releaseNote, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "releaseNote.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, releaseNote, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			releaseNoteService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "releaseNote.error.delete", e);
		}
		return redirectToList();
	}

}
