/*
 * Created on 2 Jul 2016 ( Time 10:09:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.domain;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class SqlScript implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 45 )
    private String databaseName;
    
    @Size( max = 45)
    private String title;

    @Size( max = 16777215 )
    private String script;

    @Size( max = 16777215 )
    private String comment;


    private Date datePlaced;


    private Date dateModified;

    @NotNull
    private Integer releaseNoteId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    
    public void setId( Integer id ) {
        this.id = id ;
    }

    public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDatabaseName( String databaseName ) {
        this.databaseName = databaseName;
    }
    public String getDatabaseName() {
        return this.databaseName;
    }

    public void setScript( String script ) {
        this.script = script;
    }
    public String getScript() {
        return this.script;
    }

    public void setComment( String comment ) {
        this.comment = comment;
    }
    public String getComment() {
        return this.comment;
    }

    public void setDatePlaced( Date datePlaced ) {
        this.datePlaced = datePlaced;
    }
    public Date getDatePlaced() {
        return this.datePlaced;
    }

    public void setDateModified( Date dateModified ) {
        this.dateModified = dateModified;
    }
    public Date getDateModified() {
        return this.dateModified;
    }

    public void setReleaseNoteId( Integer releaseNoteId ) {
        this.releaseNoteId = releaseNoteId;
    }
    public Integer getReleaseNoteId() {
        return this.releaseNoteId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        return this.title;
    } 


}
