
/*
 * Created on 4 Jul 2016 ( Time 10:11:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.techjournal.domain.jpa.SourceCodeEntity;
import com.kumasi.techjournal.mock.tool.MockValues;

public class SourceCodeEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public SourceCodeEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public SourceCodeEntity createInstance( Integer id ) {
		SourceCodeEntity entity = new SourceCodeEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setSourceName( mockValues.nextString(65) ) ; // java.lang.String 
		entity.setComment( mockValues.nextString(16777215) ) ; // java.lang.String 
		entity.setDatePlaced( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDateModified( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setSourceType( TODO ) ; // SourceType 
		// setTechNote( TODO ) ; // TechNote 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<SourceCodeEntity> createList(int count) {
		List<SourceCodeEntity> list = new LinkedList<SourceCodeEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
