
/*
 * Created on 4 Jul 2016 ( Time 10:14:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.techjournal.domain.jpa.SprintEntity;
import com.kumasi.techjournal.mock.tool.MockValues;

public class SprintEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public SprintEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public SprintEntity createInstance( Integer id ) {
		SprintEntity entity = new SprintEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setComment( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setStartDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setEndDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDatePlaced( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDateModified( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setApplication( TODO ) ; // Application 
		// setListOfTechNote( TODO ) ; // List<TechNote> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<SprintEntity> createList(int count) {
		List<SprintEntity> list = new LinkedList<SprintEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
