
/*
 * Created on 4 Jul 2016 ( Time 10:14:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.techjournal.domain.jpa.TechNoteEntity;
import com.kumasi.techjournal.mock.tool.MockValues;

public class TechNoteEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public TechNoteEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public TechNoteEntity createInstance( Integer id ) {
		TechNoteEntity entity = new TechNoteEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setTitle( mockValues.nextString(200) ) ; // java.lang.String 
		entity.setSprint( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setComment( mockValues.nextString(16777215) ) ; // java.lang.String 
		entity.setDatePlaced( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDateModified( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setListOfSourceCode( TODO ) ; // List<SourceCode> 
		// setSprint2( TODO ) ; // Sprint 
		// setListOfReleaseNote( TODO ) ; // List<ReleaseNote> 
		// setApplication( TODO ) ; // Application 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<TechNoteEntity> createList(int count) {
		List<TechNoteEntity> list = new LinkedList<TechNoteEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
