/*
 * Created on 2 Jul 2016 ( Time 10:09:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.techjournal.domain.ReleaseNote;
import com.kumasi.techjournal.domain.jpa.ReleaseNoteEntity;
import com.kumasi.techjournal.domain.jpa.TechNoteEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ReleaseNoteServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ReleaseNoteServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ReleaseNoteEntity' to 'ReleaseNote'
	 * @param releaseNoteEntity
	 */
	public ReleaseNote mapReleaseNoteEntityToReleaseNote(ReleaseNoteEntity releaseNoteEntity) {
		if(releaseNoteEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ReleaseNote releaseNote = map(releaseNoteEntity, ReleaseNote.class);

		//--- Link mapping ( link to TechNote )
		if(releaseNoteEntity.getTechNote() != null) {
			releaseNote.setTechNoteId(releaseNoteEntity.getTechNote().getId());
		}
		return releaseNote;
	}
	
	/**
	 * Mapping from 'ReleaseNote' to 'ReleaseNoteEntity'
	 * @param releaseNote
	 * @param releaseNoteEntity
	 */
	public void mapReleaseNoteToReleaseNoteEntity(ReleaseNote releaseNote, ReleaseNoteEntity releaseNoteEntity) {
		if(releaseNote == null) {
			return;
		}

		//--- Generic mapping 
		map(releaseNote, releaseNoteEntity);

		//--- Link mapping ( link : releaseNote )
		if( hasLinkToTechNote(releaseNote) ) {
			TechNoteEntity techNote1 = new TechNoteEntity();
			techNote1.setId( releaseNote.getTechNoteId() );
			releaseNoteEntity.setTechNote( techNote1 );
		} else {
			releaseNoteEntity.setTechNote( null );
		}

	}
	
	/**
	 * Verify that TechNote id is valid.
	 * @param TechNote TechNote
	 * @return boolean
	 */
	private boolean hasLinkToTechNote(ReleaseNote releaseNote) {
		if(releaseNote.getTechNoteId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}