/*
 * Created on 2 Jul 2016 ( Time 10:09:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.techjournal.domain.RestCall;
import com.kumasi.techjournal.domain.jpa.RestCallEntity;
import com.kumasi.techjournal.domain.jpa.ReleaseNoteEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class RestCallServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public RestCallServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'RestCallEntity' to 'RestCall'
	 * @param restCallEntity
	 */
	public RestCall mapRestCallEntityToRestCall(RestCallEntity restCallEntity) {
		if(restCallEntity == null) {
			return null;
		}

		//--- Generic mapping 
		RestCall restCall = map(restCallEntity, RestCall.class);

		//--- Link mapping ( link to ReleaseNote )
		if(restCallEntity.getReleaseNote() != null) {
			restCall.setReleaseNoteId(restCallEntity.getReleaseNote().getId());
		}
		return restCall;
	}
	
	/**
	 * Mapping from 'RestCall' to 'RestCallEntity'
	 * @param restCall
	 * @param restCallEntity
	 */
	public void mapRestCallToRestCallEntity(RestCall restCall, RestCallEntity restCallEntity) {
		if(restCall == null) {
			return;
		}

		//--- Generic mapping 
		map(restCall, restCallEntity);

		//--- Link mapping ( link : restCall )
		if( hasLinkToReleaseNote(restCall) ) {
			ReleaseNoteEntity releaseNote1 = new ReleaseNoteEntity();
			releaseNote1.setId( restCall.getReleaseNoteId() );
			restCallEntity.setReleaseNote( releaseNote1 );
		} else {
			restCallEntity.setReleaseNote( null );
		}

	}
	
	/**
	 * Verify that ReleaseNote id is valid.
	 * @param ReleaseNote ReleaseNote
	 * @return boolean
	 */
	private boolean hasLinkToReleaseNote(RestCall restCall) {
		if(restCall.getReleaseNoteId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}