/*
 * Created on 2 Jul 2016 ( Time 10:09:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.techjournal.domain.SourceType;
import com.kumasi.techjournal.domain.jpa.SourceTypeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class SourceTypeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public SourceTypeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'SourceTypeEntity' to 'SourceType'
	 * @param sourceTypeEntity
	 */
	public SourceType mapSourceTypeEntityToSourceType(SourceTypeEntity sourceTypeEntity) {
		if(sourceTypeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		SourceType sourceType = map(sourceTypeEntity, SourceType.class);

		return sourceType;
	}
	
	/**
	 * Mapping from 'SourceType' to 'SourceTypeEntity'
	 * @param sourceType
	 * @param sourceTypeEntity
	 */
	public void mapSourceTypeToSourceTypeEntity(SourceType sourceType, SourceTypeEntity sourceTypeEntity) {
		if(sourceType == null) {
			return;
		}

		//--- Generic mapping 
		map(sourceType, sourceTypeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}