/*
 * Created on 2 Jul 2016 ( Time 10:09:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.techjournal.domain.TechNote;
import com.kumasi.techjournal.domain.jpa.TechNoteEntity;
import com.kumasi.techjournal.domain.jpa.ApplicationEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TechNoteServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TechNoteServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TechNoteEntity' to 'TechNote'
	 * @param techNoteEntity
	 */
	public TechNote mapTechNoteEntityToTechNote(TechNoteEntity techNoteEntity) {
		if(techNoteEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TechNote techNote = map(techNoteEntity, TechNote.class);

		//--- Link mapping ( link to Application )
		if(techNoteEntity.getApplication() != null) {
			techNote.setApplicationId(techNoteEntity.getApplication().getId());
		}
		return techNote;
	}
	
	/**
	 * Mapping from 'TechNote' to 'TechNoteEntity'
	 * @param techNote
	 * @param techNoteEntity
	 */
	public void mapTechNoteToTechNoteEntity(TechNote techNote, TechNoteEntity techNoteEntity) {
		if(techNote == null) {
			return;
		}

		//--- Generic mapping 
		map(techNote, techNoteEntity);

		//--- Link mapping ( link : techNote )
		if( hasLinkToApplication(techNote) ) {
			ApplicationEntity application1 = new ApplicationEntity();
			application1.setId( techNote.getApplicationId() );
			techNoteEntity.setApplication( application1 );
		} else {
			techNoteEntity.setApplication( null );
		}

	}
	
	/**
	 * Verify that Application id is valid.
	 * @param Application Application
	 * @return boolean
	 */
	private boolean hasLinkToApplication(TechNote techNote) {
		if(techNote.getApplicationId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}