/*
 * Created on 4 Jul 2016 ( Time 10:14:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.techjournal.domain.jpa.ApplicationEntity;
import com.kumasi.techjournal.persistence.commons.fake.GenericFakeService;
import com.kumasi.techjournal.persistence.services.ApplicationPersistence;

/**
 * Fake persistence service implementation ( entity "Application" )
 *
 * @author Telosys Tools Generator
 */
public class ApplicationPersistenceFAKE extends GenericFakeService<ApplicationEntity> implements ApplicationPersistence {

	public ApplicationPersistenceFAKE () {
		super(ApplicationEntity.class);
	}
	
	protected ApplicationEntity buildEntity(int index) {
		ApplicationEntity entity = new ApplicationEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(ApplicationEntity entity) {
		log("delete ( ApplicationEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ApplicationEntity entity) {
		log("insert ( ApplicationEntity : " + entity + ")" ) ;
	}

	public ApplicationEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ApplicationEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ApplicationEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ApplicationEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ApplicationEntity save(ApplicationEntity entity) {
		log("insert ( ApplicationEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ApplicationEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
