/*
 * Created on 4 Jul 2016 ( Time 10:11:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.techjournal.domain.jpa.ReleaseNoteEntity;
import com.kumasi.techjournal.persistence.commons.fake.GenericFakeService;
import com.kumasi.techjournal.persistence.services.ReleaseNotePersistence;

/**
 * Fake persistence service implementation ( entity "ReleaseNote" )
 *
 * @author Telosys Tools Generator
 */
public class ReleaseNotePersistenceFAKE extends GenericFakeService<ReleaseNoteEntity> implements ReleaseNotePersistence {

	public ReleaseNotePersistenceFAKE () {
		super(ReleaseNoteEntity.class);
	}
	
	protected ReleaseNoteEntity buildEntity(int index) {
		ReleaseNoteEntity entity = new ReleaseNoteEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setTicketNumber( nextString() ) ;
		entity.setDatePlaced( nextDate() ) ;
		entity.setComment( nextString() ) ;
		entity.setDateModified( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(ReleaseNoteEntity entity) {
		log("delete ( ReleaseNoteEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ReleaseNoteEntity entity) {
		log("insert ( ReleaseNoteEntity : " + entity + ")" ) ;
	}

	public ReleaseNoteEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ReleaseNoteEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ReleaseNoteEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ReleaseNoteEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ReleaseNoteEntity save(ReleaseNoteEntity entity) {
		log("insert ( ReleaseNoteEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ReleaseNoteEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
