/*
 * Created on 4 Jul 2016 ( Time 10:11:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.techjournal.domain.jpa.RestCallEntity;
import com.kumasi.techjournal.persistence.commons.fake.GenericFakeService;
import com.kumasi.techjournal.persistence.services.RestCallPersistence;

/**
 * Fake persistence service implementation ( entity "RestCall" )
 *
 * @author Telosys Tools Generator
 */
public class RestCallPersistenceFAKE extends GenericFakeService<RestCallEntity> implements RestCallPersistence {

	public RestCallPersistenceFAKE () {
		super(RestCallEntity.class);
	}
	
	protected RestCallEntity buildEntity(int index) {
		RestCallEntity entity = new RestCallEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setRestUrl( nextString() ) ;
		entity.setApiKey( nextString() ) ;
		entity.setComment( nextString() ) ;
		entity.setDatePlaced( nextDate() ) ;
		entity.setDateModified( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(RestCallEntity entity) {
		log("delete ( RestCallEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(RestCallEntity entity) {
		log("insert ( RestCallEntity : " + entity + ")" ) ;
	}

	public RestCallEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<RestCallEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<RestCallEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<RestCallEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public RestCallEntity save(RestCallEntity entity) {
		log("insert ( RestCallEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<RestCallEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
