/*
 * Created on 4 Jul 2016 ( Time 10:11:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.techjournal.domain.jpa.SourceTypeEntity;
import com.kumasi.techjournal.persistence.commons.fake.GenericFakeService;
import com.kumasi.techjournal.persistence.services.SourceTypePersistence;

/**
 * Fake persistence service implementation ( entity "SourceType" )
 *
 * @author Telosys Tools Generator
 */
public class SourceTypePersistenceFAKE extends GenericFakeService<SourceTypeEntity> implements SourceTypePersistence {

	public SourceTypePersistenceFAKE () {
		super(SourceTypeEntity.class);
	}
	
	protected SourceTypeEntity buildEntity(int index) {
		SourceTypeEntity entity = new SourceTypeEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setCodeName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(SourceTypeEntity entity) {
		log("delete ( SourceTypeEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(SourceTypeEntity entity) {
		log("insert ( SourceTypeEntity : " + entity + ")" ) ;
	}

	public SourceTypeEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<SourceTypeEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<SourceTypeEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<SourceTypeEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public SourceTypeEntity save(SourceTypeEntity entity) {
		log("insert ( SourceTypeEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<SourceTypeEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
