/*
 * Created on 4 Jul 2016 ( Time 10:11:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.techjournal.domain.jpa.SourceCodeEntity;
import com.kumasi.techjournal.persistence.commons.fake.GenericFakeService;
import com.kumasi.techjournal.persistence.services.SourceCodePersistence;

/**
 * Fake persistence service implementation ( entity "SourceCode" )
 *
 * @author Telosys Tools Generator
 */
public class SourceCodePersistenceFAKE extends GenericFakeService<SourceCodeEntity> implements SourceCodePersistence {

	public SourceCodePersistenceFAKE () {
		super(SourceCodeEntity.class);
	}
	
	protected SourceCodeEntity buildEntity(int index) {
		SourceCodeEntity entity = new SourceCodeEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setSourceName( nextString() ) ;
		entity.setComment( nextString() ) ;
		entity.setDatePlaced( nextDate() ) ;
		entity.setDateModified( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(SourceCodeEntity entity) {
		log("delete ( SourceCodeEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(SourceCodeEntity entity) {
		log("insert ( SourceCodeEntity : " + entity + ")" ) ;
	}

	public SourceCodeEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<SourceCodeEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<SourceCodeEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<SourceCodeEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public SourceCodeEntity save(SourceCodeEntity entity) {
		log("insert ( SourceCodeEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<SourceCodeEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
