/*
 * Created on 4 Jul 2016 ( Time 10:14:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.techjournal.domain.jpa.SprintEntity;
import com.kumasi.techjournal.persistence.commons.fake.GenericFakeService;
import com.kumasi.techjournal.persistence.services.SprintPersistence;

/**
 * Fake persistence service implementation ( entity "Sprint" )
 *
 * @author Telosys Tools Generator
 */
public class SprintPersistenceFAKE extends GenericFakeService<SprintEntity> implements SprintPersistence {

	public SprintPersistenceFAKE () {
		super(SprintEntity.class);
	}
	
	protected SprintEntity buildEntity(int index) {
		SprintEntity entity = new SprintEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setName( nextString() ) ;
		entity.setComment( nextString() ) ;
		entity.setStartDate( nextDate() ) ;
		entity.setEndDate( nextDate() ) ;
		entity.setDatePlaced( nextDate() ) ;
		entity.setDateModified( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(SprintEntity entity) {
		log("delete ( SprintEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(SprintEntity entity) {
		log("insert ( SprintEntity : " + entity + ")" ) ;
	}

	public SprintEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<SprintEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<SprintEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<SprintEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public SprintEntity save(SprintEntity entity) {
		log("insert ( SprintEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<SprintEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
