/*
 * Created on 4 Jul 2016 ( Time 10:11:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.techjournal.domain.jpa.SqlScriptEntity;
import com.kumasi.techjournal.persistence.commons.fake.GenericFakeService;
import com.kumasi.techjournal.persistence.services.SqlScriptPersistence;

/**
 * Fake persistence service implementation ( entity "SqlScript" )
 *
 * @author Telosys Tools Generator
 */
public class SqlScriptPersistenceFAKE extends GenericFakeService<SqlScriptEntity> implements SqlScriptPersistence {

	public SqlScriptPersistenceFAKE () {
		super(SqlScriptEntity.class);
	}
	
	protected SqlScriptEntity buildEntity(int index) {
		SqlScriptEntity entity = new SqlScriptEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setDatabaseName( nextString() ) ;
		entity.setScript( nextString() ) ;
		entity.setComment( nextString() ) ;
		entity.setDatePlaced( nextDate() ) ;
		entity.setDateModified( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(SqlScriptEntity entity) {
		log("delete ( SqlScriptEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(SqlScriptEntity entity) {
		log("insert ( SqlScriptEntity : " + entity + ")" ) ;
	}

	public SqlScriptEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<SqlScriptEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<SqlScriptEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<SqlScriptEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public SqlScriptEntity save(SqlScriptEntity entity) {
		log("insert ( SqlScriptEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<SqlScriptEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
