/*
 * Created on 4 Jul 2016 ( Time 10:14:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.techjournal.domain.jpa.TechNoteEntity;
import com.kumasi.techjournal.persistence.commons.fake.GenericFakeService;
import com.kumasi.techjournal.persistence.services.TechNotePersistence;

/**
 * Fake persistence service implementation ( entity "TechNote" )
 *
 * @author Telosys Tools Generator
 */
public class TechNotePersistenceFAKE extends GenericFakeService<TechNoteEntity> implements TechNotePersistence {

	public TechNotePersistenceFAKE () {
		super(TechNoteEntity.class);
	}
	
	protected TechNoteEntity buildEntity(int index) {
		TechNoteEntity entity = new TechNoteEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setTitle( nextString() ) ;
		entity.setSprint( nextString() ) ;
		entity.setComment( nextString() ) ;
		entity.setDatePlaced( nextDate() ) ;
		entity.setDateModified( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(TechNoteEntity entity) {
		log("delete ( TechNoteEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(TechNoteEntity entity) {
		log("insert ( TechNoteEntity : " + entity + ")" ) ;
	}

	public TechNoteEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<TechNoteEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<TechNoteEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<TechNoteEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public TechNoteEntity save(TechNoteEntity entity) {
		log("insert ( TechNoteEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<TechNoteEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
