/*
 * Created on 2 Jul 2016 ( Time 10:09:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.kumasi.techjournal.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "batch_job"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="batch_job", catalog="techJournal" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="BatchJobEntity.countAll", query="SELECT COUNT(x) FROM BatchJobEntity x" )
} )
public class BatchJobEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="job_name", length=45)
    private String     jobName      ;

    @Column(name="file_name", length=65)
    private String     fileName     ;

    @Column(name="data")
    private String     data         ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_placed")
    private Date       datePlaced   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_modified")
    private Date       dateModified ;

	// "releaseNoteId" (column "release_note_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="release_note_id", referencedColumnName="id")
    private ReleaseNoteEntity releaseNote ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BatchJobEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : job_name ( VARCHAR ) 
    public void setJobName( String jobName ) {
        this.jobName = jobName;
    }
    public String getJobName() {
        return this.jobName;
    }

    //--- DATABASE MAPPING : file_name ( VARCHAR ) 
    public void setFileName( String fileName ) {
        this.fileName = fileName;
    }
    public String getFileName() {
        return this.fileName;
    }

    //--- DATABASE MAPPING : data ( MEDIUMTEXT ) 
    public void setData( String data ) {
        this.data = data;
    }
    public String getData() {
        return this.data;
    }

    //--- DATABASE MAPPING : date_placed ( DATETIME ) 
    public void setDatePlaced( Date datePlaced ) {
        this.datePlaced = datePlaced;
    }
    public Date getDatePlaced() {
        return this.datePlaced;
    }

    //--- DATABASE MAPPING : date_modified ( DATETIME ) 
    public void setDateModified( Date dateModified ) {
        this.dateModified = dateModified;
    }
    public Date getDateModified() {
        return this.dateModified;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setReleaseNote( ReleaseNoteEntity releaseNote ) {
        this.releaseNote = releaseNote;
    }
    public ReleaseNoteEntity getReleaseNote() {
        return this.releaseNote;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(jobName);
        sb.append("|");
        sb.append(fileName);
        // attribute 'data' not usable (type = String Long Text)
        sb.append("|");
        sb.append(datePlaced);
        sb.append("|");
        sb.append(dateModified);
        return sb.toString(); 
    } 

}
