/*
 * Created on 2 Jul 2016 ( Time 10:09:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.kumasi.techjournal.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "source_code"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="source_code", catalog="techJournal" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SourceCodeEntity.countAll", query="SELECT COUNT(x) FROM SourceCodeEntity x" )
} )
public class SourceCodeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="source_name", length=65)
    private String     sourceName   ;

    @Column(name="comment")
    private String     comment      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_placed")
    private Date       datePlaced   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_modified")
    private Date       dateModified ;

	// "sourceTypeId" (column "source_type_id") is not defined by itself because used as FK in a link 
	// "techNoteId" (column "tech_note_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="source_type_id", referencedColumnName="id")
    private SourceTypeEntity sourceType  ;

    @ManyToOne
    @JoinColumn(name="tech_note_id", referencedColumnName="id")
    private TechNoteEntity techNote    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SourceCodeEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : source_name ( VARCHAR ) 
    public void setSourceName( String sourceName ) {
        this.sourceName = sourceName;
    }
    public String getSourceName() {
        return this.sourceName;
    }

    //--- DATABASE MAPPING : comment ( MEDIUMTEXT ) 
    public void setComment( String comment ) {
        this.comment = comment;
    }
    public String getComment() {
        return this.comment;
    }

    //--- DATABASE MAPPING : date_placed ( DATETIME ) 
    public void setDatePlaced( Date datePlaced ) {
        this.datePlaced = datePlaced;
    }
    public Date getDatePlaced() {
        return this.datePlaced;
    }

    //--- DATABASE MAPPING : date_modified ( DATETIME ) 
    public void setDateModified( Date dateModified ) {
        this.dateModified = dateModified;
    }
    public Date getDateModified() {
        return this.dateModified;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setSourceType( SourceTypeEntity sourceType ) {
        this.sourceType = sourceType;
    }
    public SourceTypeEntity getSourceType() {
        return this.sourceType;
    }

    public void setTechNote( TechNoteEntity techNote ) {
        this.techNote = techNote;
    }
    public TechNoteEntity getTechNote() {
        return this.techNote;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(sourceName);
        // attribute 'comment' not usable (type = String Long Text)
        sb.append("|");
        sb.append(datePlaced);
        sb.append("|");
        sb.append(dateModified);
        return sb.toString(); 
    } 

}
