/*
 * Created on 2 Jul 2016 ( Time 10:09:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.kumasi.techjournal.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "sql_script"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="sql_script", catalog="techJournal" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SqlScriptEntity.countAll", query="SELECT COUNT(x) FROM SqlScriptEntity x" )
} )
public class SqlScriptEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="title", length=45)
    private String     title ;
    
    @Column(name="database_name", length=45)
    private String     databaseName ;

    @Column(name="script")
    private String     script       ;

    @Column(name="comment")
    private String     comment      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_placed")
    private Date       datePlaced   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_modified")
    private Date       dateModified ;

	// "releaseNoteId" (column "release_note_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="release_note_id", referencedColumnName="id")
    private ReleaseNoteEntity releaseNote ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SqlScriptEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    
    //--- DATABASE MAPPING : database_name ( VARCHAR ) 
	public String getDatabaseName() {
        return this.databaseName;
    }

    public void setDatabaseName( String databaseName ) {
        this.databaseName = databaseName;
    }
    public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}


    //--- DATABASE MAPPING : script ( MEDIUMTEXT ) 
    public void setScript( String script ) {
        this.script = script;
    }
    public String getScript() {
        return this.script;
    }

    //--- DATABASE MAPPING : comment ( MEDIUMTEXT ) 
    public void setComment( String comment ) {
        this.comment = comment;
    }
    public String getComment() {
        return this.comment;
    }

    //--- DATABASE MAPPING : date_placed ( DATETIME ) 
    public void setDatePlaced( Date datePlaced ) {
        this.datePlaced = datePlaced;
    }
    public Date getDatePlaced() {
        return this.datePlaced;
    }

    //--- DATABASE MAPPING : date_modified ( DATETIME ) 
    public void setDateModified( Date dateModified ) {
        this.dateModified = dateModified;
    }
    public Date getDateModified() {
        return this.dateModified;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setReleaseNote( ReleaseNoteEntity releaseNote ) {
        this.releaseNote = releaseNote;
    }
    public ReleaseNoteEntity getReleaseNote() {
        return this.releaseNote;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(databaseName);
        // attribute 'script' not usable (type = String Long Text)
        // attribute 'comment' not usable (type = String Long Text)
        sb.append("|");
        sb.append(datePlaced);
        sb.append("|");
        sb.append(dateModified);
        return sb.toString(); 
    } 

}
