/*
 * Created on 2 Jul 2016 ( Time 10:09:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service;

import java.util.List;

import com.kumasi.techjournal.domain.Application;

/**
 * Business Service Interface for entity Application.
 */
public interface ApplicationService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Application findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Application> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Application save(Application entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Application update(Application entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Application create(Application entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
