/*
 * Created on 2 Jul 2016 ( Time 10:09:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service;

import java.util.List;

import com.kumasi.techjournal.domain.BatchJob;

/**
 * Business Service Interface for entity BatchJob.
 */
public interface BatchJobService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	BatchJob findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<BatchJob> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	BatchJob save(BatchJob entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	BatchJob update(BatchJob entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	BatchJob create(BatchJob entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
