/*
 * Created on 2 Jul 2016 ( Time 10:09:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service;

import java.util.List;

import com.kumasi.techjournal.domain.ReleaseNote;

/**
 * Business Service Interface for entity ReleaseNote.
 */
public interface ReleaseNoteService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ReleaseNote findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ReleaseNote> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ReleaseNote save(ReleaseNote entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ReleaseNote update(ReleaseNote entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ReleaseNote create(ReleaseNote entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
