/*
 * Created on 2 Jul 2016 ( Time 10:09:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service;

import java.util.List;

import com.kumasi.techjournal.domain.SourceCode;

/**
 * Business Service Interface for entity SourceCode.
 */
public interface SourceCodeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	SourceCode findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<SourceCode> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	SourceCode save(SourceCode entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	SourceCode update(SourceCode entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	SourceCode create(SourceCode entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
