/*
 * Created on 2 Jul 2016 ( Time 10:09:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service;

import java.util.List;

import com.kumasi.techjournal.domain.SourceType;

/**
 * Business Service Interface for entity SourceType.
 */
public interface SourceTypeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	SourceType findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<SourceType> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	SourceType save(SourceType entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	SourceType update(SourceType entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	SourceType create(SourceType entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
