/*
 * Created on 4 Jul 2016 ( Time 10:15:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service;

import java.util.List;

import com.kumasi.techjournal.domain.Sprint;

/**
 * Business Service Interface for entity Sprint.
 */
public interface SprintService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Sprint findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Sprint> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Sprint save(Sprint entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Sprint update(Sprint entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Sprint create(Sprint entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
