/*
 * Created on 2 Jul 2016 ( Time 10:09:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service;

import java.util.List;

import com.kumasi.techjournal.domain.SqlScript;

/**
 * Business Service Interface for entity SqlScript.
 */
public interface SqlScriptService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	SqlScript findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<SqlScript> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	SqlScript save(SqlScript entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	SqlScript update(SqlScript entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	SqlScript create(SqlScript entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
