/*
 * Created on 2 Jul 2016 ( Time 10:09:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.business.service;

import java.util.List;

import com.kumasi.techjournal.domain.TechNote;

/**
 * Business Service Interface for entity TechNote.
 */
public interface TechNoteService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	TechNote findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TechNote> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TechNote save(TechNote entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TechNote update(TechNote entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TechNote create(TechNote entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
