/*
 * Created on 2 Jul 2016 ( Time 10:09:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.techjournal.test.persistence;


import com.kumasi.techjournal.domain.jpa.SourceTypeEntity;
import com.kumasi.techjournal.mock.SourceTypeEntityMock;
import com.kumasi.techjournal.persistence.PersistenceServiceProvider;
import com.kumasi.techjournal.persistence.services.SourceTypePersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for SourceType persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class SourceTypePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		SourceTypePersistence service = PersistenceServiceProvider.getService(SourceTypePersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test SourceType persistence : delete + load ..." );
		
		SourceTypePersistence service = PersistenceServiceProvider.getService(SourceTypePersistence.class);
		
		SourceTypeEntityMock mock = new SourceTypeEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(SourceTypePersistence service, SourceTypeEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		SourceTypeEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
